version: '3'
services:
  web:
    depends_on:
      - rates-refresher
      - rates
    build:
      context: ./fe
      dockerfile: Dockerfile.dev
    volumes:
      - ./fe/src:/app/src
      - ./fe/public:/app/public
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'

  rates-refresher:
    env_file: .env
    build:
      context: ./rates-refresher
      dockerfile: Dockerfile
    volumes:
      - ./data/btc:/data/btc
      - ./data/fiats:/data/fiats
    command: >
      /bin/bash -c "
      cp -f /data/btc/latest.example.json /data/btc/latest.json
      && cp -f /data/fiats/latest.example.json /data/fiats/latest.json
      && nodemon ./jobs.js"

  rates:
    container_name: rates
    build:
      context: ./be
      dockerfile: Dockerfile
    volumes:
      - ./data/btc:/data/btc
      - ./data/fiats:/data/fiats
    ports:
      - '8080:8080'

  nginx:
    image: nginx
    depends_on:
      - web
      - rates
    volumes:
      - ./nginx/:/etc/nginx/
      - ./logs:/logs
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - '${WEB_SERVER_PORT:-80}:${NGINX_PORT}'
      - 443:443
    env_file: ./.env
    # `envsubst '$$NGINX_PORT'` esnures envsubst only replaces NGINX_PORT with value in template
    # and do not replace vars used by nginx.conf like $HOST
    command: /bin/bash -c "
      envsubst '$$NGINX_PORT' < /etc/nginx/template/nginx.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
