version: '3'
services:
  web:
    depends_on:
      - rates-refresher
      - rates
    build:
      context: ./fe
      dockerfile: Dockerfile.prod
    volumes:
      - ./fe/src:/app/src
      - ./fe/public:/app/public
    environment:
      - NODE_ENV=production
    ports:
      - '80:80'

  rates-refresher:
    env_file: .env
    build:
      context: ./rates-refresher
      dockerfile: Dockerfile
    volumes:
      - ./data/btc:/data/btc
      - ./data/fiats:/data/fiats
    command: >
      /bin/bash -c "
      cp -f /data/btc/latest.example.json /data/btc/latest.json
      && cp -f /data/fiats/latest.example.json /data/fiats/latest.json
      && nodemon ./jobs.js"

  rates:
    container_name: rates
    build:
      context: ./be
      dockerfile: Dockerfile
    volumes:
      - ./data/btc:/data/btc
      - ./data/fiats:/data/fiats
    network_mode: host
    ports:
      - '8080:8080'