version: '3'
services:
  app:
    build:
      context: ./fe
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/data
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
      - '80:80'