version: '3'
services:
  # api:
  #   build: ../cryptojumps-backend
  #   volumes:
  #     - ../crypto-data/:/data
  #   ports:
  #   - '8080:8080'
  www:
    build: ./fe
    volumes:
      - ./data/:/data
    ports:
      - '${WEB_SERVER_PORT:-80}:${NGINX_PORT}'
    environment:
      - NODE_ENV=development
  # cron:
  #   build: ./be
  #   env_file:
  #    - ../cryptojumps-backend/.env.production
  #   volumes:
  #     - ../crypto-data/:/data
