version: '3'
services:
  web:
    container_name: web
    build:
      context: ./fe
      dockerfile: Dockerfile.dev
    volumes:
      - ./fe/src:/app/src
      - ./fe/public:/app/public
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'

  cron:
    env_file: ./.env
    build:
      context: ./cron
      dockerfile: Dockerfile
    volumes:
      - ./data/btc:/data/btc
      - ./data/fiats:/data/fiats

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - web
    volumes:
      - ./nginx/:/etc/nginx/
      - ./fe/public/:/var/www/test1/
    ports:
      - '${WEB_SERVER_PORT:-80}:${NGINX_PORT}'
    # Set env for nginx container so envsubst replace it in template
    environment:
      - NGINX_PORT=${NGINX_PORT}
    # Replace NGINX_PORT with env value.
    # We tell envsubst to onrly replace NGINX_PORT by using '$$NGINX_PORT'
    # so vars like $host used by nginx will not be replaced
    # https://github.com/docker-library/docs/issues/496#issuecomment-203003827
    # https://serverfault.com/questions/577370/how-can-i-use-environment-variables-in-nginx-conf#comment1061946_755541
    # https://stackoverflow.com/questions/21866477/nginx-use-environment-variables/57891894#57891894
    command: /bin/bash -c "envsubst '$$NGINX_PORT' < /etc/nginx/template/nginx.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"