version: '3'
services:
  web:
    container_name: web
    build:
      context: ./fe
      dockerfile: Dockerfile.dev
    volumes:
      - ./fe/src:/app/src
      - ./fe/public:/app/public
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'

  cron:
    env_file: ./.env
    build:
      context: ./cron
      dockerfile: Dockerfile
    volumes:
      - ./data/btc:/data/btc
      - ./data/fiats:/data/fiats

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - web
    volumes:
      - ./nginx/:/etc/nginx/
      - ./fe/public/:/var/www/test1/
    ports:
      - '80:80'
    links:
      - web:web