version: '3'
services:
  web:
    container_name: web
    build:
      context: ./fe
      dockerfile: Dockerfile.dev
    volumes:
      - ./fe/src:/app/src
      - ./fe/public:/app/public
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'

  cron:
    env_file: ./.env
    build:
      context: ./cron
      dockerfile: Dockerfile
    volumes:
      - ./data/btc:/data/btc
      - ./data/fiats:/data/fiats

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - web
    volumes:
      - ./nginx/:/etc/nginx/
      - ./fe/public/:/var/www/test1/
    ports:
      - '${WEB_SERVER_PORT}:${NGINX_PORT}'
    # Set nginx port from .env
    environment:
      - NGINX_PORT=${NGINX_PORT}
    # We also need this env replace NGINX_PORT with value from .env
    command: /bin/bash -c "envsubst < /etc/nginx/template/nginx.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"