version: '3'
services:
  web:
    depends_on:
      - rates_refresher
    build:
      context: ./fe
      dockerfile: Dockerfile.dev
    volumes:
      - ./fe/src:/app/src
      - ./fe/public:/app/public
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'

  rates_refresher:
    env_file: .env
    build:
      context: ./rates_refresher
      dockerfile: Dockerfile
    volumes:
      - ./data/btc:/data/btc
      - ./data/fiats:/data/fiats
    command: >
      /bin/bash -c "
      cp -f /data/btc/latest.example.json /data/btc/latest.json
      && cp -f /data/fiats/latest.example.json /data/fiats/latest.json
      && nodemon ./jobs.js"

  nginx:
    image: nginx
    depends_on:
      - web
    volumes:
      - ./nginx/:/etc/nginx/
      - ./fe/public/:/var/www/test1/
    ports:
      - '${WEB_SERVER_PORT:-80}:${NGINX_PORT}'
    env_file: ./.env
    # `envsubst '$$NGINX_PORT'` esnures envsubst only replaces NGINX_PORT with value in template
    # and do not replace vars used by nginx.conf like $HOST
    command: /bin/bash -c "
      envsubst '$$NGINX_PORT' < /etc/nginx/template/nginx.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
