version: '3'
services:
  www:
    build:
      context: ./fe
      dockerfile: Dockerfile.dev
    volumes:
      - ./fe:/usr/src/
      - '/usr/src/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
      - '80:80'