export default [
  {"name":"Afghanistan","code":"AF","currency":"AFN","population":"35530081"},
  {"name":"Åland Islands","code":"AX"},
  {"name":"Albania","code":"AL","currency":"ALL","population":"2930187"},
  {"name":"Algeria","code":"DZ","currency":"DZD","population":"41318142"},
  {"name":"AndorrA","code":"AD"},
  {"name":"Angola","code":"AO","currency":"AOA","population":"29784193"},
  {"name":"Anguilla","code":"AI","currency":"XCD","population":"14909"},
  {"name":"Antarctica","code":"AQ","currency":"XCD","population":null},
  {"name":"Antigua and Barbuda","code":"AG","currency":"XCD","population":"102012"},
  {"name":"Argentina","code":"AR","currency":"ARS","population":"44271041"},
  {"name":"Armenia","code":"AM","currency":"AMD","population":"2930450"},
  {"name":"Aruba","code":"AW","currency":"AWG","population":"105264"},
  {"name":"Australia","code":"AU","currency":"AUD","population":"24450561"},
  {"name":"Austria","code":"AT","currency":"EUR","population":"8735453"},
  {"name":"Azerbaijan","code":"AZ","currency":"AZN","population":"9827589"},
  {"name":"Bahamas","code":"BS","currency":"BSD","population":"395361"},
  {"name":"Bahrain","code":"BH","currency":"BHD","population":"1492584"},
  {"name":"Bangladesh","code":"BD","currency":"BDT","population":"164669751"},
  {"name":"Barbados","code":"BB","currency":"BBD","population":"285719"},
  {"name":"Belarus","code":"BY","currency":"BYN","population":"9468338"},
  {"name":"Belgium","code":"BE","currency":"EUR","population":"11429336"},
  {"name":"Belize","code":"BZ","currency":"BZD","population":"374681"},
  {"name":"Benin","code":"BJ","currency":"XOF","population":"11175692"},
  {"name":"Bermuda","code":"BM","currency":"BMD","population":"61349"},
  {"name":"Bhutan","code":"BT","currency":"BTN","population":"807610"},
  {"name":"Bolivia","code":"BO","currency":"BOB","population":"11051600"},
  {"name":"Bosnia and Herzegovina","code":"BA","currency":null,"population":"3507017"},
  {"name":"Botswana","code":"BW","currency":"BWP","population":"2291661"},
  {"name":"Bouvet Island","code":"BV"},
  {"name":"Brazil","code":"BR","currency":"BRL","population":"209288278"},
  {"name":"Brunei Darussalam","code":"BN"},
  {"name":"Bulgaria","code":"BG","currency":"BGN","population":"7084571"},
  {"name":"Burkina Faso","code":"BF","currency":"XOF","population":"19193382"},
  {"name":"Burundi","code":"BI","currency":"BIF","population":"10864245"},
  {"name":"Cambodia","code":"KH","currency":"KHR","population":"16005373"},
  {"name":"Cameroon","code":"CM","currency":"XAF","population":"24053727"},
  {"name":"Canada","code":"CA","currency":"CAD","population":"36624199"},
  {"name":"Cape Verde","code":"CV","currency":"CVE","population":"546388"},
  {"name":"Cayman Islands","code":"KY","currency":"KYD","population":"61559"},
  {"name":"Central African Republic","code":"CF","currency":"XAF","population":"4659080"},
  {"name":"Chad","code":"TD","currency":null,"population":"14899994"},
  {"name":"Chile","code":"CL","currency":"CLP","population":"18054726"},
  {"name":"China","code":"CN","currency":"CNY","population":"1409517397"},
  {"name":"Christmas Island","code":"CX","currency":"AUD","population":"2500"},
  {"name":"Cocos (Keeling) Islands","code":"CC","currency":"AUD","population":"600"},
  {"name":"Colombia","code":"CO","currency":"COP","population":"49065615"},
  {"name":"Comoros","code":"KM","currency":"KMF","population":"813912"},
  {"name":"Congo","code":"CG","currency":"XAF","population":"5260750"},
  {"name":"Congo, The Democratic Republic of the","code":"CD"},
  {"name":"Cook Islands","code":"CK","currency":"NZD","population":"17380"},
  {"name":"Costa Rica","code":"CR","currency":"CRC","population":"4905769"},
  {"name":"Cote D\"Ivoire","code":"CI"},
  {"name":"Croatia","code":"HR","currency":"HRK","population":"4189353"},
  {"name":"Cuba","code":"CU","currency":"CUP","population":"11484636"},
  {"name":"Cyprus","code":"CY","currency":"EUR","population":"1179551"},
  {"name":"Czech Republic","code":"CZ","currency":null,"population":"10618303"},
  {"name":"Denmark","code":"DK","currency":"DKK","population":"5733551"},
  {"name":"Djibouti","code":"DJ","currency":"DJF","population":"956985"},
  {"name":"Dominica","code":"DM","currency":"XCD","population":"73925"},
  {"name":"Dominican Republic","code":"DO","currency":"DOP","population":"10766998"},
  {"name":"Ecuador","code":"EC","currency":"ECS","population":"16624858"},
  {"name":"Egypt","code":"EG","currency":"EGP","population":"97553151"},
  {"name":"El Salvador","code":"SV","currency":"SVC","population":"6377853"},
  {"name":"Equatorial Guinea","code":"GQ","currency":"XAF","population":"1267689"},
  {"name":"Eritrea","code":"ER","currency":"ERN","population":"5068831"},
  {"name":"Estonia","code":"EE","currency":"EUR","population":"1309632"},
  {"name":"Ethiopia","code":"ET","currency":"ETB","population":"104957438"},
  {"name":"Falkland Islands (Malvinas)","code":"FK"},
  {"name":"Faroe Islands","code":"FO","currency":"DKK","population":"49290"},
  {"name":"Fiji","code":"FJ", "currency": "FJD", "population": "926276"},
  {"name":"Finland","code":"FI","currency":"EUR","population":"5523231"},
  {"name":"France","code":"FR","currency":"EUR","population":"64979548"},
  {"name":"French Guiana","code":"GF","currency":"EUR","population":"282731"},
  {"name":"French Polynesia","code":"PF","currency":"XPF","population":"283007"},
  {"name":"French Southern Territories","code":"TF"},
  {"name":"Gabon","code":"GA","currency":"XAF","population":"2025137"},
  {"name":"Gambia","code":"GM","currency":"GMD","population":"2100568"},
  {"name":"Georgia","code":"GE","currency":"GEL","population":"3912061"},
  {"name":"Germany","code":"DE","currency":"EUR","population":"82114224"},
  {"name":"Ghana","code":"GH","currency":"GHS","population":"28833629"},
  {"name":"Gibraltar","code":"GI","currency":"GIP","population":"34571"},
  {"name":"Greece","code":"GR","currency":"EUR","population":"11159773"},
  {"name":"Greenland","code":"GL","currency":"DKK","population":"56480"},
  {"name":"Grenada","code":"GD","currency":"XCD","population":"107825"},
  {"name":"Guadeloupe","code":"GP","currency":null,"population":"449568"},
  {"name":"Guam","code":"GU","currency":null,"population":"164229"},
  {"name":"Guatemala","code":"GT","currency":"QTQ","population":"16913503"},
  {"name":"Guernsey","code":"GG"},
  {"name":"Guinea","code":"GN","currency":"GNF","population":"12717176"},
  {"name":"Guinea-Bissau","code":"GW","currency":null,"population":"1861283"},
  {"name":"Guyana","code":"GY","currency":"GYD","population":"777859"},
  {"name":"Haiti","code":"HT","currency":"HTG","population":"10981229"},
  {"name":"Heard Island and Mcdonald Islands","code":"HM"},
  {"name":"Holy See (Vatican City State)","code":"VA","currency":null,"population":"1000"},
  {"name":"Honduras","code":"HN","currency":"HNL","population":"9265067"},
  {"name":"Hong Kong","code":"HK","currency":"HKD","population":"7364883"},
  {"name":"Hungary","code":"HU","currency":"HUF","population":"9721559"},
  {"name":"Iceland","code":"IS","currency":"ISK","population":"335025"},
  {"name":"India","code":"IN","currency":"INR","population":"1339180127"},
  {"name":"Indonesia","code":"ID","currency":"IDR","population":"263991379"},
  {"name":"Iran, Islamic Republic Of","code":"IR"},
  {"name":"Iraq","code":"IQ","currency":"IQD","population":"38274618"},
  {"name":"Ireland","code":"IE","currency":"EUR","population":"4761657"},
  {"name":"Isle of Man","code":"IM"},
  {"name":"Israel","code":"IL","currency":"ILS","population":"8321570"},
  {"name":"Italy","code":"IT","currency":"EUR","population":"59359900"},
  {"name":"Jamaica","code":"JM","currency":"JMD","population":"2890299"},
  {"name":"Japan","code":"JP","currency":"JPY","population":"127484450"},
  {"name":"Jersey","code":"JE"},
  {"name":"Jordan","code":"JO","currency":"JOD","population":"9702353"},
  {"name":"Kazakhstan","code":"KZ","currency":null,"population":"18204499"},
  {"name":"Kenya","code":"KE","currency":"KES","population":"49699862"},
  {"name":"Kiribati","code":"KI","currency":"AUD","population":"116398"},
  {"name":"Korea, Democratic People\"S Republic of","code":"KP"},
  {"name":"Korea, Republic of","code":"KR"},
  {"name":"Kuwait","code":"KW","currency":"KWD","population":"4136528"},
  {"name":"Kyrgyzstan","code":"KG","currency":"KGS","population":"6045117"},
  {"name":"Lao People\"S Democratic Republic","code":"LA"},
  {"name":"Latvia","code":"LV","currency":"LVL","population":"1949670"},
  {"name":"Lebanon","code":"LB","currency":"LBP","population":"6082357"},
  {"name":"Lesotho","code":"LS","currency":"LSL","population":"2233339"},
  {"name":"Liberia","code":"LR","currency":"LRD","population":"4731906"},
  {"name":"Libyan Arab Jamahiriya","code":"LY","currency":null,"population":"5605000"},
  {"name":"Liechtenstein","code":"LI","currency":"CHF","population":"37922"},
  {"name":"Lithuania","code":"LT","currency":"LTL","population":"2890297"},
  {"name":"Luxembourg","code":"LU","currency":"EUR","population":"583455"},
  {"name":"Macao","code":"MO","currency":null,"population":"473000"},
  {"name":"Macedonia, The Former Yugoslav Republic of","code":"MK"},
  {"name":"Madagascar","code":"MG","currency":"MGF","population":"25570895"},
  {"name":"Malawi","code":"MW","currency":"MWK","population":"18622104"},
  {"name":"Malaysia","code":"MY","currency":"MYR","population":"31624264"},
  {"name":"Maldives","code":"MV","currency":"MVR","population":"436330"},
  {"name":"Mali","code":"ML","currency":"XOF","population":"18541980"},
  {"name":"Malta","code":"MT","currency":"EUR","population":"430835"},
  {"name":"Martinique","code":"MQ","currency":null,"population":"384896"},
  {"name":"Mauritania","code":"MR","currency":"MRO","population":"4420184"},
  {"name":"Mauritius","code":"MU","currency":"MUR","population":"1265138"},
  {"name":"Mayotte","code":"YT","currency":"EUR","population":"253045"},
  {"name":"Mexico","code":"MX","currency":"MXN","population":"129163276"},
  {"name":"Micronesia, Federated States of","code":"FM","currency":null,"population":null},
  {"name":"Moldova, Republic of","code":"MD"},
  {"name":"Monaco","code":"MC","currency":"EUR","population":"38695"},
  {"name":"Mongolia","code":"MN","currency":"MNT","population":"3075647"},
  {"name":"Montserrat","code":"MS","currency":"XCD","population":"5177"},
  {"name":"Morocco","code":"MA","currency":"MAD","population":"35739580"},
  {"name":"Mozambique","code":"MZ","currency":"MZN","population":"29668834"},
  {"name":"Myanmar","code":"MM","currency":"MMR","population":"53370609"},
  {"name":"Namibia","code":"NA","currency":"NAD","population":"2533794"},
  {"name":"Nauru","code":"NR","currency":"AUD","population":"11359"},
  {"name":"Nepal","code":"NP","currency":"NPR","population":"29304998"},
  {"name":"Netherlands","code":"NL","currency":"EUR","population":"17035938"},
  {"name":"Netherlands Antilles","code":"AN","currency":"ANG","population":"217000"},
  {"name":"New Caledonia","code":"NC","currency":null,"population":"276255"},
  {"name":"New Zealand","code":"NZ","currency":"NZD","population":"4705818"},
  {"name":"Nicaragua","code":"NI","currency":"NIO","population":"6217581"},
  {"name":"Niger","code":"NE","currency":"XOF","population":"21477348"},
  {"name":"Nigeria","code":"NG","currency":"NGN","population":"190886311"},
  {"name":"Niue","code":"NU","currency":"NZD","population":"1618"},
  {"name":"Norfolk Island","code":"NF","currency":"AUD","population":"2000"},
  {"name":"Norway","code":"NO","currency":"NOK","population":"5305383"},
  {"name":"Oman","code":"OM","currency":"OMR","population":"4636262"},
  {"name":"Pakistan","code":"PK","currency":"PKR","population":"197015955"},
  {"name":"Palestinian Territory, Occupied","code":"PS"},
  {"name":"Panama","code":"PA","currency":"PAB","population":"4098587"},
  {"name":"Papua New Guinea","code":"PG","currency":"PGK","population":"8251162"},
  {"name":"Paraguay","code":"PY","currency":"PYG","population":"6811297"},
  {"name":"Peru","code":"PE","currency":"PEN","population":"32165485"},
  {"name":"Philippines","code":"PH","currency":"PHP","population":"104918090"},
  {"name":"Pitcairn","code":"PN","currency":null,"population":"50"},
  {"name":"Poland","code":"PL","currency":"PLN","population":"38170712"},
  {"name":"Portugal","code":"PT","currency":"EUR","population":"10329506"},
  {"name":"Qatar","code":"QA","currency":"QAR","population":"2639211"},
  {"name":"Reunion","code":"RE","currency":null,"population":"699000"},
  {"name":"Romania","code":"RO","currency":"RON","population":"19679306"},
  {"name":"Russian Federation","code":"RU","currency":null,"population":"143989754"},
  {"name":"RWANDA","code":"RW"},
  {"name":"Saint Helena","code":"SH","currency":"SHP","population":"4049"},
  {"name":"Saint Kitts and Nevis","code":"KN","currency":null,"population":"55345"},
  {"name":"Saint Lucia","code":"LC","currency":"XCD","population":"178844"},
  {"name":"Saint Pierre and Miquelon","code":"PM","currency":"EUR","population":"6320"},
  {"name":"Saint Vincent and the Grenadines","code":"VC","currency":"XCD","population":"109897"},
  {"name":"Samoa","code":"WS","currency":"WST","population":"196440"},
  {"name":"San Marino","code":"SM","currency":"EUR","population":"33400"},
  {"name":"Sao Tome and Principe","code":"ST","currency":"STD","population":"204327"},
  {"name":"Saudi Arabia","code":"SA","currency":"SAR","population":"32938213"},
  {"name":"Senegal","code":"SN","currency":"XOF","population":"15850567"},
  {"name":"Serbia","code":"RS", "currency": "RSD", "population": "6963764"},
  {"name":"Seychelles","code":"SC","currency":"SCR","population":"94737"},
  {"name":"Sierra Leone","code":"SL","currency":"SLL","population":"7557212"},
  {"name":"Singapore","code":"SG","currency":"SGD","population":"5708844"},
  {"name":"Slovakia","code":"SK","currency":"EUR","population":"5447662"},
  {"name":"Slovenia","code":"SI","currency":"EUR","population":"2079976"},
  {"name":"Solomon Islands","code":"SB","currency":"SBD","population":"611343"},
  {"name":"Somalia","code":"SO","currency":"SOS","population":"14742523"},
  {"name":"South Africa","code":"ZA","currency":"ZAR","population":"56717156"},
  {"name":"South Georgia and the South Sandwich Islands","code":"GS","currency":"GBP","population":null},
  {"name":"Spain","code":"ES","currency":"EUR","population":"46354321"},
  {"name":"Sri Lanka","code":"LK"},
  {"name":"Sudan","code":"SD","currency":"SDG","population":"40533330"},
  {"name":"Suriname","code":"SR","currency":"SRD","population":"563402"},
  {"name":"Svalbard and Jan Mayen","code":"SJ","currency":null,"population":"3200"},
  {"name":"Swaziland","code":"SZ","currency":"SZL","population":"1008000"},
  {"name":"Sweden","code":"SE","currency":"SEK","population":"9910701"},
  {"name":"Switzerland","code":"CH","currency":"CHF","population":"8476005"},
  {"name":"Syrian Arab Republic","code":"SY"},
  {"name":"Taiwan, Province of China","code":"TW"},
  {"name":"Tajikistan","code":"TJ","currency":"TJS","population":"8921343"},
  {"name":"Tanzania, United Republic of","code":"TZ"},
  {"name":"Thailand","code":"TH","currency":"THB","population":"69037513"},
  {"name":"Timor-Leste","code":"TL"},
  {"name":"Togo","code":"TG","currency":"XOF","population":"7797694"},
  {"name":"Tokelau","code":"TK","currency":"NZD","population":"1300"},
  {"name":"Tonga","code":"TO","currency":"TOP","population":"108020"},
  {"name":"Trinidad and Tobago","code":"TT","currency":"TTD","population":"1369125"},
  {"name":"Tunisia","code":"TN","currency":"TND","population":"11532127"},
  {"name":"Turkey","code":"TR","currency":"TRY","population":"80745020"},
  {"name":"Turkmenistan","code":"TM","currency":"TMT","population":"5758075"},
  {"name":"Turks and Caicos Islands","code":"TC","currency":null,"population":"35446"},
  {"name":"Tuvalu","code":"TV","currency":"AUD","population":"11192"},
  {"name":"Uganda","code":"UG","currency":"UGX","population":"42862958"},
  {"name":"Ukraine","code":"UA","currency":"UAH","population":"44222947"},
  {"name":"United Arab Emirates","code":"AE","currency":"AED","population":"9400145"},
  {"name":"United Kingdom","code":"GB","currency":'GBP',"population":"66181585"},
  {"name":"United States","code":"US","currency":'USD',"population":"324459463"},
  {"name":"United States Minor Outlying Islands","code":"UM","currency":null,"population":null},
  {"name":"Uruguay","code":"UY","currency":"UYU","population":"3456750"},
  {"name":"Uzbekistan","code":"UZ","currency":"UZS","population":"31910641"},
  {"name":"Vanuatu","code":"VU","currency":"VUV","population":"276244"},
  {"name":"Venezuela","code":"VE","currency":"VEF","population":"31977065"},
  {"name":"Viet Nam","code":"VN"},
  {"name":"Virgin Islands, British","code":"VG","currency":null,"population":null},
  {"name":"Virgin Islands, U.S.","code":"VI","currency":null,"population":null},
  {"name":"Wallis and Futuna","code":"WF","currency":null,"population":"11773"},
  {"name":"Western Sahara","code":"EH","currency":"MAD","population":"552628"},
  {"name":"Yemen","code":"YE","currency":"YER","population":"28250420"},
  {"name":"Zambia","code":"ZM","currency":"ZMW","population":"17094130"},
  {"name":"Zimbabwe","code":"ZW","currency":"ZWD","population":"16529904"}
]