# base image
FROM node:12.2.0-alpine

USER root

# set working directory
RUN mkdir /app
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

RUN npm install react-scripts@1.1.1 -g --silent
RUN npm install typescript -g --silent
RUN npm install node-sass@latest -g --unsafe-perm --silent

# install and cache app dependencies
COPY tsconfig.json /app/tsconfig.json
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

RUN npm install --silent

# start app
CMD ["npm", "start"]